#define userCreated			1
#define	defaultInbox			2
#define defaultDrafts			3
#define	defaultDeletedItems		4
#define	defaultSentItems		5
#define	defaultOutbox			6
#define	defaultTasks			7
#define	defaultCalendar			8
#define	defaultContacts			9
#define	defaultNotes			10
#define	defaultJournal			11
#define	userCreatedMail			12
#define	userCreatedCalendar		13
#define	userCreatedContacts		14
#define	userCreatedTasks		15
#define	userCreatedJournal		16
#define	userCreatedNotes		17
#define	unknown				18
#define	recipentInformationCache	19
